### ISSUE TITLE
Difference with pydantic-spark?

### ISSUE THREAD

**Issue by timvancann** [mitchelllisle/sparkdantic#378]
There already exists a library that seems to have similar features:  https://github.com/godatadriven/pydantic-spark
Please provide some reason / differences to choose this over the other, or vice versa.

**Comment by mitchelllisle** [comment]
Hi @timvancann 
Thank you for the link! I wasn't aware of this project. It's always beneficial for the community to have options and nice to see others tackling the same challenges. I think its always positive where different solutions can coexist and cater to varied preferences and requirements and I don't think that just because something exists that excludes others from tackling similar problems.

**Comment by timvancann** [comment]
I never meant for this repo not to exist; I apologize if that was how my message came across.
From a use perspective, I was merely looking for the differences between the two and when to choose which. Since this one is the newer (and more active repo), I incorrectly assumed that you've tried the other repo and found it lacking :).

**Comment by dan1elt0m** [comment]
Hey @timvancann, sparkdantic has feature parity with pydantic-spark and i'd recommend using sparkdantic. pydantic-spark is hard to maintain and its author is not maintaining any of the libraries inside the godatadriven space anymore.
